<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Algorithms\" />
    <Folder Include="Metrics\" />
    <Folder Include="Services\" />
    <Folder Include="Simulation\" />
  </ItemGroup>

</Project>
